name: Frontiers
main: net.williserver.frontiers.FrontiersPlugin
version: 1.0
api-version: 1.21

commands:
  frontiers:
    description: Frontiers root command.
    usage: "Usage: /frontiers [get | open | close | inc | dec]"

permissions:
  frontiers.get:
    description: Allows /frontiers get
    default: true
  frontiers.open:
    description: Allows /frontiers open
    default: op
  frontiers.close:
    description: Allows /frontiers close
    default: op
  frontiers.inc:
    description: Allows /frontiers inc
    default: op
  frontiers.dec:
    description: Allows /frontiers dec
    default: op